name: Deploy para Firebase (Hosting + Functions)

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout do Código
        uses: actions/checkout@v4

      - name: 🟢 Setup Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: 📦 Instalar Dependências do Projeto
        run: npm ci

      - name: 💾 Restaurar Cache do Next.js
        uses: actions/cache@v4
        with:
          path: .next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.js', '**/*.jsx', '**/*.ts', '**/*.tsx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

      - name: 🏗️ Build do Next.js
        run: npm run build
        env:
          NEXT_PUBLIC_FIREBASE_API_KEY: "AIzaSyCZjcmdQ2PjK7quZyWgUaGHOAdEeBj7y_U"
          NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN: "lucianatf-8395f.firebaseapp.com"
          NEXT_PUBLIC_FIREBASE_PROJECT_ID: "lucianatf-8395f"
          NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET: "lucianatf-8395f.firebasestorage.app"
          NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: "222698045073"
          NEXT_PUBLIC_FIREBASE_APP_ID: "1:222698045073:web:4b2b68a7c6a392946f4930"

      - name: 🧹 Limpar Cache do Next.js antes do Deploy
        run: rm -rf .next/cache

      - name: 📦 Instalar Dependências das Functions
        working-directory: ./functions
        run: npm install

      - name: 🚀 Preparar SSR (Copy .next para Functions)
        run: |
          rm -rf functions/.next
          cp -r .next functions/

      - name: 🔑 Autenticação no Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_LUCIANATF_8395F }}

      - name: ☁️ Deploy para o Firebase
        run: |
          npx firebase-tools deploy --only hosting,functions --project lucianatf-8395f --non-interactive --force
